# action.yml
name: "Hello World"
description: "Greet someone and record the time"
inputs:
  token:
    description: "The github token"
    required: true
  pullRequest:
    description: "The pull request to take the last comment"
    required: true
outputs:
  message: # id of output
    description: "Last commit message of PR"
runs:
  using: "docker"
  image: "Dockerfile"
